watercrawl_contracts:
  outputs:
    ci:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'analytics/target/contracts.duckdb') }}"
      schema: main
      threads: 4
      external_root: "{{ env_var('DBT_EXTERNAL_ROOT', 'analytics/external') }}"
    local:
      type: duckdb
      path: "{{ env_var('DBT_DUCKDB_PATH', 'analytics/target/contracts.duckdb') }}"
      schema: main
      threads: 4
      external_root: "{{ env_var('DBT_EXTERNAL_ROOT', 'analytics/external') }}"
  target: ci
