config:
  default: true
  MD013:
    line_length: 600
    heading_line_length: 200
    code_block_line_length: 600
    tables: false
  MD033: false
  MD041: false
  MD046:
    style: fenced
  MD036: false
  MD028: false
ignores:
  - dist/**
  - analytics/target/**
  - node_modules/**
