extends: default
rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  document-start:
    present: false
ignore: |
  dist/**
  analytics/target/**
  .mypy_cache/**
  .pytest_cache/**
  **/node_modules/**
  **/pnpm-lock.yaml
  docs-starlight/**/pnpm-lock.yaml
  catalog-info.yaml
  templates/golden-path/catalog-info.yaml
  .venv/**
  **/.venv/**
