# DEPRECATED: This MkDocs configuration is obsolete
# The project now uses Starlight (Astro-based) for documentation
# Please refer to docs-starlight/ for the current documentation
#
# This file is kept for reference only and will be removed in a future version
# Visit https://IAmJonoBo.github.io/watercrawl for the live documentation

site_name: ACES Aerodynamics Enrichment Stack (DEPRECATED)
site_description: "Data enrichment, validation, and automation toolkit for South African flight school intelligence."
site_author: ACES Aerodynamics Analyst
repo_url: https://github.com/acesaero/watercrawl
nav:
  - Home: index.md
  - Gap Analysis: gap-analysis.md
  - Architecture: architecture.md
  - ADRs:
      - Overview: adr/index.md
      - Segmented Package Boundaries: adr/0001-architecture-boundaries.md
  - Data Quality & Research: data-quality.md
  - CLI Guide: cli.md
  - Surface Taxonomy: surface-taxonomy.md
  - MCP Integration: mcp.md
  - Operations: operations.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
