[[blockers]]
package = "dbt-extractor"
targets = ["3.14", "3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.14+"
notes = "Blocks dbt contract execution until upstream ships cp314/cp315 wheels."

[[blockers]]
package = "duckdb"
targets = ["3.14", "3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.14+"
notes = "Required for SQLFluff/dbt smoke tests; coordinate with upstream release schedule."

[[blockers]]
package = "psutil"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "Impacts observability and cleanup tooling; monitor psutil 7.x release milestones."

[[blockers]]
package = "pyarrow"
targets = ["3.14", "3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.14+"
notes = "Lakehouse pipelines and dbt adapters require official cp314/cp315 wheels."

[[blockers]]
package = "tornado"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "Needed for Streamlit/Jupyter developer surfaces; ensure Renovate PRs capture blocker context."

[[blockers]]
package = "deltalake"
targets = ["3.14", "3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.14+"
notes = "Lakehouse Delta snapshots require upstream cp314/cp315 wheels before enabling newer interpreters."

[[blockers]]
package = "arro3-core"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "Arrow3 core bindings required by scrapy lack cp314/cp315 wheels; monitor upstream builds."

[[blockers]]
package = "jstyleson"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "JSON style tooling used by extruct has no cp314/cp315 wheels; track release cadence."

[[blockers]]
package = "libcst"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "LibCST does not yet publish cp314/cp315 wheels; Renovate should surface upstream releases."

[[blockers]]
package = "lxml"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "HTML parsing stack depends on lxml wheels; wait for cp314/cp315 support before bumping interpreters."

[[blockers]]
package = "pypydispatcher"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "Scrapy transitively requires pypydispatcher; upstream must publish cp314/cp315 wheels."

[[blockers]]
package = "zope-interface"
targets = ["3.14", "3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.14+"
notes = "Twisted dependency zope-interface needs cp314/cp315 wheels before interpreter bump."

[[blockers]]
package = "greenlet"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Playwright depends on greenlet; block Python 3.15 until wheels ship."

[[blockers]]
package = "grpcio"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "OTLP exporter requires grpcio; monitor cp315 wheel availability."

[[blockers]]
package = "selectolax"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "HTML parser selectolax lacks cp315 wheels; update when upstream publishes binaries."

[[blockers]]
package = "setproctitle"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Analytics tooling relies on setproctitle; wait for cp315 support."

[[blockers]]
package = "argon2-cffi-bindings"
targets = ["3.15"]
owner = "Security"
issue = "Missing wheels for Python 3.15"
notes = "Password hashing dependencies require cp315 wheels before enabling Python 3.15."

[[blockers]]
package = "cffi"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Core dependency for cryptography stack; track upstream release cadence."

[[blockers]]
package = "cryptography"
targets = ["3.15"]
owner = "Security"
issue = "Missing wheels for Python 3.15"
notes = "TLS and secrets tooling must stay pinned until cp315 wheels ship."

[[blockers]]
package = "markupsafe"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Jinja-based tooling depends on cp315 wheels; update once upstream packages builds."

[[blockers]]
package = "msgpack"
targets = ["3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.15"
notes = "Telemetry ingestion relies on msgpack wheels; coordinate with maintainers."

[[blockers]]
package = "numpy"
targets = ["3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.15"
notes = "Scientific stack must wait for official cp315 wheels to avoid source builds."

[[blockers]]
package = "pandas"
targets = ["3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.15"
notes = "Dataframe tooling depends on cp315 wheels; align with upstream release notes."

[[blockers]]
package = "scipy"
targets = ["3.15"]
owner = "Data Engineering"
issue = "Missing wheels for Python 3.15"
notes = "Scientific computing stack needs cp315 wheels to avoid slow source builds."

[[blockers]]
package = "pillow"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Image pipelines require cp315 wheels; monitor upstream builds."

[[blockers]]
package = "pydantic-core"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Pydantic 2.x runtime needs cp315 wheels before bumping interpreters."

[[blockers]]
package = "pywinpty"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Windows developer tooling depends on cp315 wheels; gate interpreter bumps."

[[blockers]]
package = "pyyaml"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Configuration parsing relies on cp315 wheels; refresh once manylinux builds land."

[[blockers]]
package = "pyzmq"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Notebook infrastructure depends on cp315 wheels; track upstream packaging."

[[blockers]]
package = "regex"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Text processing modules require cp315 wheels prior to interpreter bumps."

[[blockers]]
package = "rpds-py"
targets = ["3.15"]
owner = "Platform"
issue = "Missing wheels for Python 3.15"
notes = "Pydantic core dependency; ensure cp315 wheels exist before enabling Python 3.15."

[[blockers]]
package = "great-expectations"
targets = ["3.14", "3.15"]
owner = "Data Engineering"
issue = "Python version unsupported"
notes = "Great Expectations 1.7.1 currently pins Python <3.14; defer interpreter bumps until upstream releases cp314/cp315 compatibility."

