# Additional problems collector tool definitions.
# Update this file to register bespoke linters, formatters, or security scanners
# without editing scripts/collect_problems.py directly.

[[tools]]
name = "pylint"
parser = "pylint"
command = [
  "pylint",
  "firecrawl_demo",
  "app",
  "scripts",
  "tests",
  "--output-format=json",
  "--score=n",
]
optional = true
enable_if_env = ["ENABLE_PYLINT"]
