name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: pip install poetry
      - name: Cache Poetry environments
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run isort check
        run: poetry run isort --profile black --check-only .
      - name: Run black check
        run: poetry run black --check .
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure
      - name: Run tests
        run: >-
          poetry run pytest --maxfail=5 --disable-warnings --cov=firecrawl_demo
          --cov-report=term-missing --cov-report=xml:coverage.xml --junitxml=pytest-results.xml
      - name: Generate CI summary
        run: |
          poetry run python -m scripts.ci_summary \
            --coverage coverage.xml \
            --junit pytest-results.xml \
            --output ci-summary.md \
            --json ci-dashboard.json
          cat ci-summary.md >> $GITHUB_STEP_SUMMARY
      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-dashboards
          path: |
            coverage.xml
            pytest-results.xml
            ci-summary.md
            ci-dashboard.json
