name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
      - name: Run tests
        run: poetry run pytest --maxfail=5 --disable-warnings --cov=firecrawl_demo --cov-report=term-missing
