name: test-with-wheelhouse
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Download wheelhouse
        uses: actions/download-artifact@v4
        with:
          name: wheelhouse-3.13
          path: wheelhouse
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      - name: Install from wheelhouse
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-index --find-links=wheelhouse -r wheel-reqs.txt
      - name: Run tests
        run: poetry run pytest -q
