name: Wheel Mirror

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches:
      - main
    paths:
      - 'poetry.lock'
  workflow_dispatch: {}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip --timeout 60 --retries 5
          python -m pip install poetry --timeout 60 --retries 5
      - name: Mirror cp314/cp315 wheels
        run: |
          python scripts/mirror_wheels.py --python 3.14 --python 3.15
      - name: Upload mirrored wheels
        uses: actions/upload-artifact@v4
        with:
          name: pip-wheel-mirror
          path: artifacts/cache/pip
      - name: Check wheel status blockers
        run: |
          python -m scripts.wheel_status --fail-on-missing
