name: Wheelhouse Producer
on:
  push:
    branches: [main]
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
  workflow_dispatch: {}

jobs:
  build-wheelhouse:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13", "3.14", "3.15"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip --timeout 60 --retries 5
          python -m pip install poetry --timeout 60 --retries 5
      - name: Create wheelhouse
        run: |
          python scripts/provision_wheelhouse.py --output wheelhouse --python ${{ matrix.python-version }}
      - name: Upload wheelhouse artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse-${{ matrix.os }}-py${{ matrix.python-version }}
          path: wheelhouse
      - name: Cache wheelhouse
        uses: actions/cache@v4
        with:
          path: wheelhouse
          key: wheelhouse-${{ matrix.os }}-py${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
